[package]
name = "gregorian"
version = "0.1.0"
license = "BSD-2-Clause"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[features]
default = ["std"]
std = []

[dev-dependencies]
assert2 = "0.2.1"
